version: '3.7'

services:
    client:
        environment:
            - REST_URL=https://server:port/api/
    server:
        image: tareita_server:latest
        build:
            context: Server
            dockerfile: Dockerfile
